### ISSUE TITLE
[Feature Request]: Make profiles/settings/playlists/history.db available to user on Android 

### ISSUE THREAD

**Issue by MartFab** [MarmadileManteater/FreeTubeCordova#152]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I was not able to find this four files (profiles.db, settings.db, playlists.db and history.db) on a android 13 (LOS20) installation.
On desktop this files are available to user so it is possible to sync this files using third-party tools (like syncthing) for exemple.
If it was the same on android it could help sync subscription and playlist across devices.

### Proposed Solution

I'm not sure of implications but it seems possible to have a filesystem interface on cordova using cordova-plugin-file.

### Alternatives Considered

Regarding the "sync" part : i know we can already import/export data from/to FreeTubeCordova but having the ability to sync this file will simplify a lot the day-to-day use.

Regarding solution : i know nothing about cordova but other filesystem interface look like more limited.

### Issue Labels

ease of use improvement, support for external software

**Comment by vdbhb59** [comment]
Not just this, with the latest build the whole database vanished and now does not get imported from the desktop exports. I lost everything even with backups.

**Comment by MarmadileManteater** [comment]
This issue has moved higher up on my priority list because I have plans to change the domain the app is hosted on again (from `localhost` to `file://`). If I don't address this issue before changing the domain, everyone will lose their subscriptions upon upgrading, so this is probably the very next thing I will address with FreeTubeCordova before the major update I am working on. My plan is to write my own `localforage` substitute which writes to the android filesystem which nedb will import in place of the regular `localforage` which stores items in localstorage.

**Comment by MarmadileManteater** [comment]
I was able to override `localforage` through webpack with no issue, and it seems like it is writing and reading to the data folders now. It is pretty 🧊cool to be able to clear to localstorage and have the app data persist.

 ![IMG_20240202_135913](https://github.com/MarmadileManteater/FreeTubeCordova/assets/106682128/e379829e-d673-40ab-af21-1c4594bd84a5)

**Comment by MarmadileManteater** [comment]
The database files should now be located at `/Android/data/io.freetubeapp.freetube.nightly/` when booting up the latest nightly on android. I'm going to test it a little more before releasing it proper, but it exists now.

**Comment by MarmadileManteater** [comment]
This issue should now be resolved by release [`0.19.2.110`](https://github.com/MarmadileManteater/FreeTubeCordova/releases/tag/0.19.2.110).
