### ISSUE TITLE
[Feature Request]: Add autocomplete suggestions to video search input field 

### ISSUE THREAD

**Issue by shadycloud** [MarmadileManteater/FreeTubeCordova#223]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When users type the first few characters into a text box on a form, they don't see a list of possible matches from among entries that they nor other users have typed before.

### Proposed Solution

I suppose I'd like to see a solution implemented in the Javascript that enables autocomplete functionality to the search input field when typing characters.

### Alternatives Considered

Perhaps a setting to turn this functionality off as well using a slide button to toggle on/off.

### Issue Labels

display more information to user, ease of use improvement, visual improvement

### Additional Information

![Screenshot_20230919_122245_Chrome](https://github.com/MarmadileManteater/FreeTubeCordova/assets/13189052/7cf13247-77eb-431c-aa48-357e595b44e4)
https://www.algolia.com/blog/engineering/how-to-implement-autocomplete-with-javascript-on-your-website/

**Comment by shadycloud** [comment]
Also, I noticed this feature request was made/closed in the upstream repo FreeTubeApp/FreeTube/
https://github.com/FreeTubeApp/FreeTube/issues/840

 If this would be a good first issue, I'd like to be assigned. 

![Screenshot_20230919_121225_FreeTube](https://github.com/MarmadileManteater/FreeTubeCordova/assets/13189052/727e1b05-5e28-454f-bc51-3ced1b2124a9)

**Comment by shadycloud** [comment]
So I noticed the following quoted message in the contributions area, but I don't know if the issue is directly related to cordova code.... I did get upstream working on ubuntu today, so I'll be looking for some low hanging fruit over that way... I'm taking a course on FOSS for college and I've never contributed anything to open source.  "Notice: MOST CHANGES SHOULD PROBABLY BE MADE TO [UPSTREAM],(https://www.github.com/freetubeapp/freetube) https://github.com/FreeTubeApp/FreeTube/issues/840 UNLESS DIRECTLY RELATED TO CORDOVA CODE OR WORKFLOWS.

If you like to get your hands dirty and want to contribute, we would love to have your help. Send a pull request and someone will review your code. Please follow the [Contribution Guidelines](https://github.com/MarmadileManteater/FreeTubeCordova/blob/development/CONTRIBUTING.md) before sending your pull request." Also I saw the upstream code that highlights the searchbar element where I figured this code would need to be located... I don't have any experience with android or ios development. I guess I'll just try and figure it out. I still complete my course goal if this feature shows up in the app through someone else coding it. If that happens I suppose I can try to hunt some inconsistent behavior bugs or some other seemingly easier feature enhancement issues.

**Comment by ChunkyProgrammer** [comment]
I think this issue is already fixed unless I'm misunderstanding? (Note: I think I have a newer build than release installed which might be a reason why it's fixed for me, it could also have to do with the Invidious Instance https://github.com/MarmadileManteater/FreeTubeCordova/actions/runs/6057928011 )

![image](https://github.com/MarmadileManteater/FreeTubeCordova/assets/78101139/6f0b43d4-4878-414d-951b-ef1eef9441d0)

"Cordova Code or workflows" => this was added to encourage people to open PRs upstream unless it had something to do with Cordova specific functionality (ex: GitHub workflows/docker images,  background play on android) or fixing something that works in upstream but doesn't work in Cordova

**Comment by shadycloud** [comment]
Interesting, yea seems to be working on your screen. I'm still able to recreate the issue on my end. Will be back with results after trying 0.19
![Screenshot_20231008_234537_FreeTube](https://github.com/MarmadileManteater/FreeTubeCordova/assets/13189052/3a067ed0-83a7-497e-bec4-af97e6420ce8)
![Screenshot_20231008_235544_FreeTube Nightly](https://github.com/MarmadileManteater/FreeTubeCordova/assets/13189052/c8ea1b09-f00a-415b-b02b-87526b09e041)
Edit: indeed fixed with the fresh install of the nightly build apk, ch33rs!!!
