### ISSUE TITLE
Any new updates/releases please?

### ISSUE THREAD

**Issue by vdbhb59** [MarmadileManteater/FreeTubeCordova#224]
Hi Emma,
Just wanted to know, if the project will be deploying any new releases please? There are many breaks in the current version from March due to several changes by the foogle front on YT. It would be real helpful if there is a new release sent out to F-Droid soon. :)

**Comment by MarmadileManteater** [comment]
There's a new release now: https://github.com/MarmadileManteater/FreeTubeCordova/releases/tag/0.19.1.109
