### ISSUE TITLE
[BUG] Quality not selectable

### ISSUE THREAD

**Issue by HarriBuh** [MarmadileManteater/FreeTubeCordova#239]
**Topic**
Please select what topic you are referring to.
- [x ] Coding
- [ ] Contribution
- [ ] Languages
- [ x] Setup
- [ ] Other. Please specify:

**Question**
After opening a YT link with the app, I am not able to change the quality setting/ resolution setting at all, while other options (captions, fullscreen etc.) work as intended.

![Screenshot_20231023-201552](https://github.com/MarmadileManteater/FreeTubeCordova/assets/123186113/54c90520-af64-427f-b848-9067c5d0b51f)

Pixel 7
Android 14
App version 0.19.1.109

**Comment by MarmadileManteater** [comment]
I'm aware the current quality selector is not particularly touch friendly. This might get better when upstream switches video players.

**Comment by HarriBuh** [comment]
Most likely not getting resolved ever.

**Comment by HarriBuh** [comment]
What is it? I hate loose ends and abandoned threads.

**Comment by MarmadileManteater** [comment]
This is low on my priority list because the video player will eventually be changing (idk when). Please, stop closing this issue. I want this issue to track the progress of this specific problem.

**Comment by MarmadileManteater** [comment]
This is now fixed in the current nightly by the upstream PR mentioned above.

**Comment by MarmadileManteater** [comment]
This is now resolved by release [0.20.0.115](https://github.com/MarmadileManteater/FreeTubeCordova/releases/tag/0.20.0.115).
