### ISSUE TITLE
[Bug]: Disabling Smooth Scrolling tries to "Restart" the web app

### ISSUE THREAD

**Issue by ChunkyProgrammer** [MarmadileManteater/FreeTubeCordova#24]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. go to settings
2. go to theme settings
3. enable "Disable Smooth Scrolling:
4. Prompt pops up to restart app
5. Website doesn't restart

### Expected Behavior

I'm not really sure what the "disable smooth scrolling" setting is supposed to do but it seems to try to require electron in order to do the restart

### Issue Labels

usability issue

### FreeTube Version

Web

### Operating System Version

Windows 11

### Installation Method

other

### Primary API used

Invidious API

### Additional Information

I'm not really sure what smooth scrolling is but this fix could probably be applied upstream, I imagine?

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
Do you think it would make sense to hide this setting when `IS_ELECTRON` is `false`? I'm not sure if we could do anything with it in web browsers or in cordova.

**Comment by ChunkyProgrammer** [comment]
Yeah, i think that would make sense

**Comment by MarmadileManteater** [comment]
The fix for this is now merged back into this fork from upstream and should be rolling out in nightly 62.
