### ISSUE TITLE
[Bug]: NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.

### ISSUE THREAD

**Issue by 110errm** [MarmadileManteater/FreeTubeCordova#243]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Start freetube on android
Search any Video
Start playing

### Expected Behavior

Playing content

### Issue Labels

API issue, feature stopped working, usability issue

### FreeTube Version

0.19.1.109

### Operating System Version

Android 13, iode os

### Installation Method

.apk

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

none

### Additional Information

Thx

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by dnltsk** [comment]
Same behaviour as described above, but error message is

```
NotSupportedError: Failed to load because no supported source was found.
```

**Comment by plant7403** [comment]
Having the same error as the one above 🫡

**Comment by MarmadileManteater** [comment]
This error has historically happened because this app relied entirely on invidious instances to proxy video sources, but the latest nightly supports streaming videos **without** using an invidious proxy. 

I would suggest trying out the latest nightly build if u r experiencing this issue: https://github.com/MarmadileManteater/FreeTubeCordova/actions/runs/8099690296

**Comment by Saschatheraccoon** [comment]
It will show a cross on the play button how do I fix that? And it on not a jailbreak iPad 1

**Comment by MarmadileManteater** [comment]
> It will show a cross on the play button how do I fix that? And it on not a jailbreak iPad 1

Could you post a screenshot of what ur seeing?
