### ISSUE TITLE
[Bug]: Checking for updates uses the wrong url

### ISSUE THREAD

**Issue by ChunkyProgrammer** [MarmadileManteater/FreeTubeCordova#25]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. open FreeTube Cordova
2. open dev tools
3. see error

### Expected Behavior

App should point to 
'https://api.github.com/repos/marmadilemanteater/freetubecordova/releases?per_page=1' instead of https://api.github.com/repos/marmadilemanteater/freetube/releases?per_page=1

### Issue Labels

feature stopped working

### FreeTube Version

Cordova

### Operating System Version

Windows 11

### Installation Method

other

### Primary API used

Invidious API

### Additional Information

Was thinking about maybe making the check electron only but android users or PWA users might want to keep the app to date so I don't think that would be the best solution. 

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
I updated the link to point to the correct release URL. This change should roll out in the next nightly 61.

**Comment by ChunkyProgrammer** [comment]
https://github.com/MarmadileManteater/FreeTubeCordova/blob/ccf1c1c60d575ff145479cd9eb169c658952b464/src/renderer/App.js#L214
I believe the logic to compare versions would also need to be changed to something like this (haven't tested it)
``` js
            const tagName = json[0].tag_name
            const versionNumber = tagName.split('-nightly-')[1]
            this.updateChangelog = marked.parse(json[0].body)
            this.changeLogTitle = json[0].name
            const message = this.$t('Version $ is now available!  Click for more details')
            this.updateBannerMessage = message.replace('$', versionNumber)
            const appVersion = version.split('-nightly-')[1]
            if (parseInt(versionNumber) > parseInt(appVersion)) {
              this.showUpdatesBanner = true
            }
```

**Comment by MarmadileManteater** [comment]
This functionality now appears to be working:
<img src="https://user-images.githubusercontent.com/106682128/198045527-8ee2aa9d-b61d-4ae9-9ce2-cd7a3a761b45.png" width="350" /> <img src="https://user-images.githubusercontent.com/106682128/198045590-d25eb84b-d6ce-41a6-a5aa-3c5cbaa69acc.png" width="350"/>

**Comment by ChunkyProgrammer** [comment]
Closing as complete
