### ISSUE TITLE
[Feature Request]: Ability to choose directory where the data is located

### ISSUE THREAD

**Issue by JustVldKsh** [MarmadileManteater/FreeTubeCordova#299]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Expands on #152 and commit that implemented it because of Android limitations on newer versions

On devices running Android 11 and newer (currently running non-rooted Android 13) it is not possible to access files located in `/storage/emulated/0/Android/` directories via normal means (that aren't SAF workarounds or ADB or USB access) thus it is not possible to sync the data via something like Syncthing (or in my case Syncthing-fork) app, which doesn't use any of the methods mentioned

### Proposed Solution

Add ability to choose where the app stores data files (if possible and most importantly reasonable, since it isn't really a problem for at least root users)

### Alternatives Considered

- Necrobumped https://github.com/Catfriend1/syncthing-android/issues/978#issuecomment-1965783393 and later will possibly create a new issue in case it goes unnoticed (since it was closed because of the person asking Shizuku API support (basically API for on-device ADB interactions) for syncing Downloads directory, which doesn't require either ADB or even root)
- Looking for file syncing alternatives that allow syncing `Android/` directories (not sure if those exist at the moment)
- Learning Android development and trying to do either of these myself (will take quite a while)
- Manually copying Freetube data between instances (inconvenient)
- Waiting until I'm able to unlock, flash and root my device (manufacturer-caused roadblocks I am going to wait through either way)

### Issue Labels

improvement to existing feature, new optional setting, support for external software

### Additional Information

"To protect your privacy, choose another folder" prompt in `Android/` and `data` missing
![Screenshot_2024-02-27-13-26-23-072_com google android documentsui](https://github.com/MarmadileManteater/FreeTubeCordova/assets/49518100/0071b1d7-4a9e-43fa-b974-1a1658613a02)

**Comment by MarmadileManteater** [comment]
I wasn't aware that it was hidden usually. CalyxOS must do something to make them visible by default. 

I think it makes perfect sense to add a setting like that.

**Comment by MarmadileManteater** [comment]
In the latest nightly, there should now be the option to select the directory where data is stored (and to reset it back to default).

![image](https://github.com/MarmadileManteater/FreeTubeCordova/assets/106682128/8baac52f-8397-4ed8-87ce-7f19081a91f9)
![image](https://github.com/MarmadileManteater/FreeTubeCordova/assets/106682128/1f1054cc-4af7-4642-b0a6-5637e3ba11bd)
![image](https://github.com/MarmadileManteater/FreeTubeCordova/assets/106682128/5e730583-ec11-49cb-96f4-1b0772a41dcf)

**Comment by JustVldKsh** [comment]
Just installed and it seems to work properly, gonna switch to FreeTube later

Thank you so much, should I close the issue since it is implemented or should it stay open until it lands in release?

**Comment by MarmadileManteater** [comment]
I typically keep it open until the release. I might eventually change that procedure, but for now, I'll leave this issue open. I'll officially close it when the next release (0.20.x?) is out.

**Comment by MarmadileManteater** [comment]
Also, as a note, if ur plans are to sync the files, freetubecordova nightly matches most closely to the upstream nightly. If u try to sync between 0.19.2 (release) and nightly cordova, u may run into issues with the playlists.db being formattted differently.

**Comment by JustVldKsh** [comment]
Yeah, already noticed the lack of proper playlists support in the latest upstream release and got the nightly a few days ago

**Comment by Aterfax** [comment]
Any chance we could also get this functionality within the Docker web app and not just the android app. Suspect a few people would like to be able to host this as a web app within their homelab with a persistent file storage backend. (aka stick it behind a secure proxy and use it as a full youtube replacement.)

**Comment by MarmadileManteater** [comment]
This is now resolved by release [0.20.0.115](https://github.com/MarmadileManteater/FreeTubeCordova/releases/tag/0.20.0.115).

**Comment by Aterfax** [comment]
Did this release also let the PWA / docker choose the directory location via the "Data Settings", Settings drop down?

**Comment by MarmadileManteater** [comment]
> Did this release also let the PWA / docker choose the directory location via the "Data Settings", Settings drop down?

No, sorry. The PWA still uses local storage. As it stands, the PWA is a bunch of static files. Adding the ability to store the data somewhere else would require a server bundled with the PWA assets. It is not undoable, but it would require a major overhaul. I have considered making a version of freetube which has a server component, unlike the current PWA. That version of freetube could potentially have all sorts of things that seemed impossible in the static files version of the PWA: local api, data storage on the filesystem, etc. However, it would also be a another set of integrations to maintain on the same scale as the android app whereas the current PWA primarily relies on code which is already maintained upstream.

**Comment by 4rg1l** [comment]
I'm getting an error like this when trying to select the data directory.

![Image](https://github.com/user-attachments/assets/ba354946-ce6e-4fb4-a4e4-3c8d608ec783)

 Am I missing something or is this a bug?

EDIT. I can export subscriptions and playlists just fine to the same directory, but it won't let me move the data directory. Also, Freetube never asked for storage permissions. Should it have?
