### ISSUE TITLE
[Bug]: Can't play video

### ISSUE THREAD

**Issue by John4650-hub** [MarmadileManteater/FreeTubeCordova#318]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

At first the videos where playing normally but today the program has failed to play any video because of some API error.
I am running *freetube as a flask application* 
This is what i got after trying the latest nightly build artifact for PWA 
```shell
The video returned by YouTube isn't the requested one. (Android client)"
errorBacktrace: "The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)↵ from src/invidious/videos/parser.cr:157:9 in 'try_fetch_streaming_data'↵ from src/invidious/videos/parser.cr:111:5 in 'extract_video_info:video_id'↵ from src/invidious/videos.cr:391:3 in 'fetch_video'↵ from src/invidious/videos.cr:379:13 in 'get_video'↵ from src/invidious/videos.cr:361:1 in 'get_video:region'↵ from src/invidious/routes/api/v1/videos.cr:12:15 in 'videos'↵ from src/invidious/routing.cr:229:5 in '->'↵ from lib/kemal/src/kemal/route.cr:12:26 in '->'↵ from src/invidious/helpers/handlers.cr:30:5 in 'process_request'↵ from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from src/invidious/helpers/handlers.cr:157:5 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from src/invidious/helpers/handlers.cr:94:12 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from src/invidious/helpers/handlers.cr:146:5 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from src/invidious/helpers/handlers.cr:70:5 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from src/ext/kemal_static_file_handler.cr:162:16 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from src/invidious/helpers/logger.cr:17:35 in 'call'↵ from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'↵ from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'↵ from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'↵ from /usr/share/crystal/src/http/server.cr:521:5 in 'handle_client'↵ from /usr/share/crystal/src/http/server.cr:451:5 in '->'↵ from /usr/share/crystal/src/fiber.cr:146:11 in 'run'↵ from /usr/share/crystal/src/fiber.cr:98:34 in '->'↵ from ???↵"
[
```
This is what i see in the browser
![Screenshot_20240330-182102](https://github.com/MarmadileManteater/FreeTubeCordova/assets/84484398/d8c87be0-b4ed-401b-9298-78c808b54a15)

### Expected Behavior

Video should have played as it used to

### Issue Labels

API issue

### FreeTube Version

v0.19.2-nightly-435 Beta

### Operating System Version

Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G532F) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/17.0 Chrome/96.0.4664.104 Mobile Safari/537.36

### Installation Method

PWA (Progressive Web App)

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
This is known issue with invidious. AFAIK, there is a new integrity check for the android endpoints (which iv relies on for streams).

iv-org/invidious#4498

There is nothing that can be done about it in freetube. The local api is not effected because it uses the web endpoints.

**Comment by karmarcharger** [comment]
> This is known issue with invidious. AFAIK, there is a new integrity check for the android endpoints (which iv relies on for streams).
> 
> [iv-org/invidious#4498](https://github.com/iv-org/invidious/issues/4498)
> 
> There is nothing that can be done about it in freetube. The local api is not effected because it uses the web endpoints.

![image](https://github.com/MarmadileManteater/FreeTubeCordova/assets/10364143/cb1cc576-e807-4366-9daa-1419fcdbb6af)
Switching to local api and opening a video still throws invidious API error tho?
![image](https://github.com/MarmadileManteater/FreeTubeCordova/assets/10364143/96162faf-167a-4d0b-afe3-f1fc83d7c02f)

**Comment by MarmadileManteater** [comment]
The PWA does not support the local api because of CORS. I should hide the api preference setting on that version, so its more clear.
