### ISSUE TITLE
Question about error: "unknown data key: lastViewedPlaylistType" when importing History to FreeTube Desktop App

### ISSUE THREAD

**Issue by OutlanderTechGeek** [MarmadileManteater/FreeTubeCordova#334]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:

**Question**
Hi! Thank you very much for your amazing work! I have just discovered the FreeTube project and this fork and am delighted to sync all my data between the desktop and Android app via Syncthing :)

Nevertheless, I am getting an error when importing my history from Android to the official desktop app. As in the title, I get a list of errors, all beginning with: "Unknown data key", followed by: lastViewedPlaylistType; LastViewedPlaylistItemId; lastViewedPlaylistType. In the end, it says that the history has been imported successfully, but that is not the case...

Anyway, I would love to hear from you soon. Sorry for my noobniness, hehehehe! 

Regards,

MissyToby

**Comment by MarmadileManteater** [comment]
I can also reproduce that message by importing my own history db file from the desktop version.

![image-2](https://github.com/MarmadileManteater/FreeTubeAndroid/assets/106682128/2cf98732-f614-49f6-821a-d58605703e35)

AFAIK, the message "unknown data key" is simply a warning that there is some extra data present in the db file which isn't being used by freetube.

https://github.com/FreeTubeApp/FreeTube/blob/ff9c9e8a7be5f646a51fb36df8ff0b62f3ae1d30/src/renderer/components/data-settings/data-settings.js#L737-L744
