### ISSUE TITLE
[Bug]: The app is keeping the screen on

### ISSUE THREAD

**Issue by sebbekm** [MarmadileManteater/FreeTubeCordova#335]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open Freetube
2. Swipe to home/switch to another app and leave the phone for as long as your screen timeout is set at. You will notice that the screen does not turn off

### Expected Behavior

It should turn off when not watching a video or when using another app.

### Issue Labels

usability issue

### FreeTube Version

v0.20.0.116

### Operating System Version

Android 13

### Installation Method

.apk

### Primary API used

Local API

### Additional Information

I have tested freetube on three devices and the bug is there on all of them. I have to force close the app, then the screen turns off as intended.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
I have noticed this too, and it bothers me, but I don't know how to fix it at the moment. The wake lock should be being released whenever the app goes into the background.

https://github.com/MarmadileManteater/FreeTubeAndroid/blob/7048a90a2ee0116579ac1cd3e1e2a797ebe80f04/android/app/src/main/java/io/freetubeapp/freetube/MainActivity.kt#L308C1-L316C4

However, it clearly still keeps the screen on when the phone is locked, so I don't know.

**Comment by sebbekm** [comment]
> I have noticed this too, and it bothers me, but I don't know how to fix it at the moment. The wake lock should be being released whenever the app goes into the background.
> 
> https://github.com/MarmadileManteater/FreeTubeAndroid/blob/7048a90a2ee0116579ac1cd3e1e2a797ebe80f04/android/app/src/main/java/io/freetubeapp/freetube/MainActivity.kt#L308C1-L316C4
> 
> However, it clearly still keeps the screen on when the phone is locked, so I don't know.

That's weird. I hope you find a solution

**Comment by MarmadileManteater** [comment]
~~I just pushed changes which should fix this issue. I used a different method for keeping the screen on which should only work when the app is in the foreground. You can download the nightly here to try it out: https://github.com/MarmadileManteater/FreeTubeAndroid/actions/runs/8680496645~~

nvm I actually found a problem with it.

**Comment by MarmadileManteater** [comment]
Okay, now, it should be fixed in the nightly. (sry abt that 🙈) https://github.com/MarmadileManteater/FreeTubeAndroid/actions/runs/8680564516

**Comment by sebbekm** [comment]
> Okay, now, it should be fixed in the nightly. (sry abt that 🙈) https://github.com/MarmadileManteater/FreeTubeAndroid/actions/runs/8680564516

It's working as intended on the two devices I have on me right now, awesome 👍
