### ISSUE TITLE
Youtube block third party apps

### ISSUE THREAD

**Issue by Raffy-ID** [MarmadileManteater/FreeTubeCordova#343]
**Important note**
Please check other open and closed issues for a similar discussion or a question relating to your discussion before posting a new one. 

**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [ ] Other. Please specify:
- [ ] Youtube Policy

**Discussion**
https://www.google.com/url?q=https://www.theverge.com/2024/4/15/24131338/youtube-ad-blocker-crackdown-mobile-apps&sa=U&ved=2ahUKEwjNopGn0saFAxU5b2wGHb30CJAQxfQBegQIBhAC&usg=AOvVaw3rvA-3CaGVvHfJaOORxira

Youtube now targeting third party apps as their new policy stated "all third party apps must comply with youtube API". How this is affect Freetube?

**Comment by ChunkyProgrammer** [comment]
FreeTube doesn't use YouTube's API (neither does Invidious)
