### ISSUE TITLE
Storing Subscriptions data 

### ISSUE THREAD

**Issue by John4650-hub** [MarmadileManteater/FreeTubeCordova#344]
**Important note**
Please check other open and closed issues for a similar discussion or a question relating to your discussion before posting a new one. 

**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify: storage 

**Discussion**
Ever since i started using this great software, i have been facing a problem of abrupt loss
of all subscriptions data and this happens sometimes when I clear browser cache  data. May be it's because the data is stored in the browser local storage. 

I would like to know if it's possible for you guys to **fix** this by prompting the user to download a copy of the subscriptions everytime the user subscribes to a new channel, that way, the saved subscriptions data can be imported if the browser 's data is cleared  by either the system abruptly or the user accidentally.

This will save others who might not know what has happened the frustration of losing the data and also it will save us from having to always think about when to download the subscriptions data.

Device:

|screen |360 * 640|
|-|-|
|viewport|360 * 474|
|pixel ratio|1.5|

System: 

|os|android|
|-|-|
|browser|android 6|

**User Agent:** 
Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G532F) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/17.0 Chrome/96.0.4664.104 Mobile Safari/537.36

**For some reason the APK file doesn't install on my android version so I rely on the PWA**

**Comment by MarmadileManteater** [comment]
The data is stored in local storage in the PWA. That is a limitation of it being a SPA. You can export your data in data-settings before clearing your local storage if you find that helpful.

I have considered writing a full proper server implementation (which would support things like saving `db` files); however, it is a lot of work, and there is a lot to consider. 

As for the APK not installing on your device, the app was built for android 7+, so that makes sense. I could try lowering the minimum sdk version. However, I already have several known issues with android versions <=10, so I don't think I have the bandwidth presently to support older android versions.

**Comment by John4650-hub** [comment]
@MarmadileManteater i would like to know the path to the file having the code that manages subscriptions. I want to see if am able to adjust it to what i want to do without diving into the `db stuff`.

**Comment by MarmadileManteater** [comment]
If you want to implement something along the lines of prompting the user to download their data every time they subscribe/unsubscribe, the places you want to look are in the data-settings:

https://github.com/MarmadileManteater/FreeTubeAndroid/blob/760b77a9ce355296a06f1a1eac176d14c0c465a4/src/renderer/components/data-settings/data-settings.js#L605-L623

and in the ft-subscribe-button component:

https://github.com/MarmadileManteater/FreeTubeAndroid/blob/760b77a9ce355296a06f1a1eac176d14c0c465a4/src/renderer/components/ft-subscribe-button/ft-subscribe-button.js#L100-L162

**Comment by MarmadileManteater** [comment]
I also want to clarify that I probably won't merge this feature if you implement it. I just wanted to show you where the relevant code is if you wanted to implement it for a custom build for yourself. 

Personally, I don't see any issue to fix here. The PWA relies on browser local storage for persistence. If you delete your browser storage (or have it deleted automatically when you close your browser), you should expect sites which rely on storing data locally to lose data.

I say this not to downplay the importance of the issue to you, but to clarify how I feel about the issue.

**Comment by John4650-hub** [comment]
Thanks for the big help.
