### ISSUE TITLE
Docker mount data persistence

### ISSUE THREAD

**Issue by mikki8** [MarmadileManteater/FreeTubeCordova#358]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [x] Setup
- [ ] Other. Please specify:

**Question**
Hi,
i am using the docker image on a server. and want the config+data safe outside of the container.
which folders do i have to mount into my host system ?

**Comment by MarmadileManteater** [comment]
The PWA does not store its data server side, so there is no directory to mount.

**Comment by mikki8** [comment]
oh yes this makes sense. just tested by deleting cookies and data. thank you
