### ISSUE TITLE
[Feature Request]: Release v0.21.1 Beta out today!

### ISSUE THREAD

**Issue by Samohttnias** [MarmadileManteater/FreeTubeCordova#405]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

A serious problem showed up yesterday and was brought up in the Matrix chatroom today. The problem is an inability to access the local API and then, there after, issues with the Invidious API. While these problems are solved on the desktop version, they persist in the Android version. Just wanted to alert that the new Version is out to those who make the APK!
It's not a feature request so much as a feature restoration request.

### Proposed Solution

Basic update to the new source code, allowing for a fresh APK.

### Alternatives Considered

I know it would be work, and beyond my understanding; but a version tracker would be useful for those who don't follow the desktop version as closely?

### Issue Labels

improvement to existing feature

### Additional Information

I suspect this is not the exact way to put this out there, but it is stopping me and others from using the app.

**Comment by HeheBigMan** [comment]
This change killed Newpipe for me completely, obviously no Invidious backup over there, so that feature here has saved me many headaches. Even better to see the primary API fix come in so quick as well. Mad respect.

**Comment by ACR-Jeff** [comment]
I wouldn't call this a feature request or an enhancement, It should be a bug report of a major issue.

**Comment by Samohttnias** [comment]
Understood. I wasn't sure where to post this, I was talking to the Freetube guys so I checked to see if anyone had mentioned it over here. Should I repost over on issues? or is there something a mod can do?

**Comment by MarmadileManteater** [comment]
I am working on getting the release out, but for now, the latest nightly is up to date with upstream `0.21.1`: https://github.com/MarmadileManteater/FreeTubeAndroid/actions/runs/9890328698

**Comment by MarmadileManteater** [comment]
Release 0.21.1.119 is available now. https://github.com/MarmadileManteater/FreeTubeAndroid/releases/tag/0.21.1.119
