### ISSUE TITLE
[Bug]: GUI infinite loading reloading on video selection to watch

### ISSUE THREAD

**Issue by gripfastistech** [MarmadileManteater/FreeTubeCordova#409]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

select video from main new list, video page opens, GUI goes nuts zooming in and out while trying to load content placeholders, and reload page, repeats instantly all controls lost, loops very fast loading reloading (miliseconds) (sorry for lame description)

screen recorder cannot capture bug

webview updated yesterday to 126.0.6478.186; likely cause, first run with this bug

### Expected Behavior

open new video page, play video

### Issue Labels

usability issue

### FreeTube Version

0.21.1.119

### Operating System Version

android 13 one ui 5.1 kernel 4.19

### Installation Method

.apk

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

same version previous days

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by gripfastistech** [comment]
NotSupportedError: Failed to load because no supported source was found.

**Comment by SDD701** [comment]
Probably this issue is presented in the desktop version too and it's just backports here https://github.com/FreeTubeApp/FreeTube/issues/5456

**Comment by gripfastistech** [comment]
going to try this: https://github.com/FreeTubeApp/FreeTube/issues/5456#issuecomment-2248897869

**Comment by gripfastistech** [comment]
proxy through invidious is workaround on first video test, upstream issue confirmed
