### ISSUE TITLE
[Bug]: move quickly between silence

### ISSUE THREAD

**Issue by rsssxd** [MarmadileManteater/FreeTubeCordova#413]
Video content jumps quickly between silence. There is no flag to close it.

.

### Issue Labels

inconsistent behavior

### FreeTube Version

Last version

### Operating System Version

Android 14 

### Installation Method

.apk

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

.

### Additional Information

.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
Can you please describe your issue in further detail?

**Comment by rsssxd** [comment]
Video content skips the quiet parts quickly.

**Comment by rsssxd** [comment]
Sorry I miscalculated the playback speed. 


But it would be very good if it was a full screen option.and again support picture-in-picture. When you exit the video tab, the video closes.

**Comment by MarmadileManteater** [comment]
I'm going to close this issue due to vagueness and inactivity.
