### ISSUE TITLE
NotAllowedError: Write permission denied - when copying video links

### ISSUE THREAD

**Issue by JustHere4TheShow** [MarmadileManteater/FreeTubeCordova#439]
I assume it might be due to my phone's Android version (11) or something else related to my phone, but I truly dunno what to do. I checked the app's permission list and it doesn't have any toggleable permissions.
Anything can be done about it?

Device: Samsung A02
FreeTubeAndroid version: 0.22.0-nightly-503

**Comment by JustHere4TheShow** [comment]
My bad, I think I solved it myself by copying the link found in the console log 😅

**Comment by childeofentropy** [comment]
> My bad, I think I solved it myself by copying the link found in the console log 😅

hi, i am having the same issue. how did you solved it exactly?
