### ISSUE TITLE
Proxy support missing

### ISSUE THREAD

**Issue by shadyxN8ANacSoBCJzZpjG7LyXNgNfMAbLoME** [MarmadileManteater/FreeTubeCordova#440]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [ ] Setup
- [x] Other. Please specify:

**Question**
Please write down your question.
In the README.md, it says:

> Connect to an externally setup proxy such as Tor

In the Freetube desktop client, these proxy settings are below "Data" in settings, however in the mobile app, these settings are not there.

Is there a reason? Am I missing something?
Thanks!!!

**Comment by MarmadileManteater** [comment]
That line in the readme is a mistake. This feature has not been implemented yet.

**Comment by shadyxN8ANacSoBCJzZpjG7LyXNgNfMAbLoME** [comment]
Thank you.

**Comment by Flashwalker** [comment]
Socks5 proxy is necessary

**Comment by MarmadileManteater** [comment]
valid. personally, it is not high up on my list of missing features, but it probably wouldn't hurt to have a feature request on file for it. idk.
