### ISSUE TITLE
[Bug]: Fast-Forward/Rewind Interval option is not being respected

### ISSUE THREAD

**Issue by jinwk00** [MarmadileManteater/FreeTubeCordova#442]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Set Fast-Forward/Rewind Interval to 5s in Player options
2. Watch a video
3. Double tap left or right to go forward or rewind
4. Notice it always advances 10s

### Expected Behavior

It should be going back and forth depending on option for Fast-forward/Rewind interval

### Issue Labels

feature stopped working, usability issue

### FreeTube Version

0.22.0.126

### Operating System Version

Android 15, 5.15.170-android14-11-gf0d7580141e5 #1 Sun Nov 17 15:23:20 UTC 2024

### Installation Method

.apk

### Primary API used

Invidious API

### Additional Information

May be related to issue #56 , which implemented videojs-mobile-ui

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This will be fixed by this upstream pull request: https://github.com/FreeTubeApp/FreeTube/pull/6288

**Comment by jinwk00** [comment]
Pull request merged

**Comment by jinwk00** [comment]
Seems that recently this regressed and is not working anymore, it's always -10/+10s

**Comment by absidue** [comment]
It definitely didn't regress you just never updated to a version that has the fix yet, because that version doesn't exist, as the change hasn't landed in a release yet (in upstream or in this repo).

I think you may have forgotten that you closed this when the pull request was merged (which was the correct thing to do, please close it again).

**Comment by jinwk00** [comment]
Even the latest Nightly release? That's where I am right now (specifically, 504)

**Comment by absidue** [comment]
Yes, it is only in the upstream nightlies (easy to tell if you look at the commits). It's always a massive amount of work and takes a long time to sync the repos because of all of the code conflicts and Android specific adjustments that have to be done every time, so it isn't done very often.
