### ISSUE TITLE
[Feature Request]: add an option under "player" to select the default audio language for multi-audio videos

### ISSUE THREAD

**Issue by Abdullah-Alwael** [MarmadileManteater/FreeTubeCordova#455]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The app always choose the first audio language which might be German or Spanish in random depending on the video.

### Proposed Solution

Add an option under player settings to select default audio language.

### Alternatives Considered

Manually selecting the audio after the video loads with unwanted audio stream.

### Issue Labels

new optional setting

### Additional Information

None

**Comment by MarmadileManteater** [comment]
see: https://github.com/FreeTubeApp/FreeTube/issues/4291#issuecomment-2452527942

**Comment by Abdullah-Alwael** [comment]
Thank you
