### ISSUE TITLE
Build names are going to change

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [MarmadileManteater/FreeTubeCordova#461]
Hi Emma i would like to inform you that some of our release build names are going to change and you could be affected by this, see https://github.com/FreeTubeApp/FreeTube/pull/6423

**Comment by MarmadileManteater** [comment]
ty for the notice. I don't believe it should cause any issues for me.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @MarmadileManteater asset names getting a minor adjustment, see https://github.com/FreeTubeApp/FreeTube/pull/7512
