### ISSUE TITLE
[Feature Request]: videojs-mobile-ui

### ISSUE THREAD

**Issue by ChunkyProgrammer** [MarmadileManteater/FreeTubeCordova#56]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

VideoPlayer doesn't have the best mobile controls

### Proposed Solution

Not sure if this would work in Cordova or not but the [videojs-mobile-ui](https://github.com/mister-ben/videojs-mobile-ui) module will add touch controls (such as double tap left side to rewind & right side to fast-forward). It might be good to implement this upstream if it works with Cordova.

### Alternatives Considered

None

### Issue Labels

ease of use improvement, new feature

**Comment by MarmadileManteater** [comment]
I like `videojs-mobile-ui`. It is a really quick drop-in solution which adds some nice QoL features for mobile, and testing it in Cordova, it seems to work just as well as in a web browser.

**Comment by MarmadileManteater** [comment]
One thing to note is that there may have to be some slight CSS changes due to the larger play/pause button that `videojs-mobile-ui` introduces.
![image](https://user-images.githubusercontent.com/106682128/195248855-27b0ca39-caa7-4b59-ad04-da366a52b3ce.png)

**Comment by MarmadileManteater** [comment]
These changes have been pulled in from upstream as of commit a3ffbda, and they should roll out in nightly release 72.
