### ISSUE TITLE
[Feature Request]: be free from android’s WebView

### ISSUE THREAD

**Issue by DI555** [MarmadileManteater/FreeTubeCordova#72]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

many users like to cutt the android’s WebView off from system.

### Proposed Solution

i suppose the app is using system android’s WebView engine((

so, is any chance to inject some free web engine into the .apk and use this engine ?

**Comment by MarmadileManteater** [comment]
AFAIK, Cordova uses the system default which is available on the device it is installed on, and for me personally, I use CalyxOS as my daily driver. That replaces the default android web view with a custom version of chromium. Something like this may or may not be an option for you. Although, if you are at all concerned about the default android web view and you are thinking about gutting it from your system, I would highly recommend custom roms such as [CalyxOS](https://calyxos.org/) or [GrapheneOS](https://grapheneos.org/) which both replace the default webview with their own version.

I am unsure of how to accomplish the behavior of injecting a custom webview at the app level without forking Cordova. I'm not saying it is impossible to accomplish this behavior with Cordova, but I have no idea how it would be done. I am also not exactly sure that it is in the scope of this project _(as far as the work I am personally doing)_. Someone else is free to take a shot at developing a version of Cordova _(or something similar)_ that bundles a patched version of chromium, but I do not have interest in doing that at this time.

As far as things you can do right now to avoid the default android web view without installing a custom rom or doing some root trickery, there is still the [PWA](https://marmadilemanteater.github.io/freetube/#) which you can use in any browser.

**Comment by MarmadileManteater** [comment]
I'm closing this because of what I have already stated. I don't think it is contained within the scope of this project, and I have no interest in pursuing it.

**Comment by DI555** [comment]
yep, ok, it's a pity that not possible to put html engine inside like electron uses((

it's interesting, i think, to check working of the pwa-.zip form by localy open it in a browser 🔥

**Comment by Mokura** [comment]
Most browsers are a wrapper around the default webview, right?  Notable exceptions being Firefox and Actual Chrome/ium.  If you're rooted, there are also Magisk modules to replace your default system webview with, say, Bromite.
