### ISSUE TITLE
[Bug]: Changing playback formats mid playback causes video to start from beginning 

### ISSUE THREAD

**Issue by MarmadileManteater** [MarmadileManteater/FreeTubeCordova#8]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

1. Play a video
2. Attempt to change the format from Dash to Legacy or Audio
The video begins from the beginning instead of picking up where it left of.

### Expected Behavior

The video should keep playing from the point it was at when the format was changed.

### Issue Labels

feature stopped working

### FreeTube Version

v0.16.0 66168e5

### Operating System Version

Android 11, Kernel version 4.14.180-perf+ #1 Mon Mar 28 06:29:53 CDT 2022, Build number RPMS31.Q1-54-13.3-10

### Last Known Working FreeTube Version (If Any)

This feature never worked in Cordova.

### Primary API used

Invidious API

### Additional Information

Android 11, Kernel version 4.14.180-perf+ https://github.com/MarmadileManteater/FreeTubeCordova/pull/1 Mon Mar 28 06:29:53 CDT 2022, Build number RPMS31.Q1-54-13.3-10

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
this seems to be an issue in upstream freetube as well

**Comment by MarmadileManteater** [comment]
This has always been an upstream issue, but it used to be a bigger problem for this repo back before local streaming was available. Now, changing formats behaves very similarly to upstream, working sometimes, and failing other times (whereas it used to fail most times). Considering this and the fact that Shaka does not have this race condition, this issue will be fixed upstream eventually. I don't see a reason to track it here anymore.
