### ISSUE TITLE
VT report

### ISSUE THREAD

**Issue by IzzySoft** [MarmadileManteater/FreeTubeCordova#83]
just to let you know that [VT](https://www.virustotal.com/gui/file/39e9c379db7e5b694db10f3c8e4e5d264ff3360dab86c7107c4bced139117521/detection) has a single engine reporting a most likely false positive. A concerned user just informed me. As said, I consider this a "false positive" because:

* only 1 out of 64 engines reports it (first 60, I just triggered a rescan)
* it's a rather minor engine.

"Android.WIN32.Gustuff.san" is around for more than a year – so if it were real, more than 1 engine would have reported it, including all (or at least most) of the "big ones". But still, cannot hurt taking a look and hopefully getting rid of that flag to avoid having it confuse users :wink: Thanks!

**Comment by MarmadileManteater** [comment]
I 🤔wonder if it would be worth testing a version of the app in VT with 100% of the Cordova plugins removed. Like you said, it could be a false positive, but if it is accurate, it might be coming from one of the plugins that are installed or Cordova itself; everything else is just a web app.

**Comment by IzzySoft** [comment]
Jupp. But as pointed out: just a single engine reports it, and that thingy is around long enough for even the slowest engine having it added to their signature list. So I rather think it's a false positive. Just wanted you to be aware in case someone drops in, panic stricken… :wink:
