### ISSUE TITLE
[Bug]: App crashes when playing video (lineage OS)

### ISSUE THREAD

**Issue by wikd** [MarmadileManteater/FreeTubeCordova#91]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Launch app
2. Click video
3. Video page loads momentarily then crashes

### Expected Behavior

Click link and video to play.

### Issue Labels

causes crash

### FreeTube Version

0.18.0.98

### Operating System Version

android 10, android 12 both on lineage os.

### Installation Method

.apk

### Primary API used

Invidious API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by MarmadileManteater** [comment]
When you say "crash", can you describe further what you mean? Does the app fully close? Or does the app hang and become fully unresponsive? Or does something else happen?

**Comment by wikd** [comment]
The app fully closes.

**Comment by MarmadileManteater** [comment]
I was able to replicate this issue on one of my devices which uses CalyxOS. _(ik its not the exact same as lineage, but its another custom rom)_. From what it looks like, the plugins: `cordova-plugin-music-controls2` and `cordova-plugin-advanced-background-mode` are causing the crashes. If I remove them, the app seems to work fine (albeit there is no background play). I'm going to troubleshoot this further.

**Comment by MarmadileManteater** [comment]
I upgraded `cordova-plugin-music-controls2` to the newest version and the crash that occurred for me when watching videos seems to have gone away. I'm going to push up those changes in a bit, and then, if you would like, you can try out that nightly: https://github.com/MarmadileManteater/FreeTubeCordova/actions/runs/3998526419 It may partially resolve this issue; however, the background play plugin will still cause crashes when trying to play the video in the background.

**Comment by MarmadileManteater** [comment]
And for further clarification, it might also be worth turning on the `Disable notification when app in background` setting under `Cordova Settings` as it seems that the notification is what might be causing the crash when the video is in the background.

**Comment by ChunkyProgrammer** [comment]
You could try using this fork and maybe it'll work (haven't checked it out too much) @MarmadileManteater  https://bitbucket.org/TheBosZ/cordova-plugin-run-in-background/src/master/

**Comment by MarmadileManteater** [comment]
> You could try using this fork and maybe it'll work (haven't checked it out too much) @MarmadileManteater https://bitbucket.org/TheBosZ/cordova-plugin-run-in-background/src/master/

I tried it out, and it seems to work better than the other background mode plugin on both my devices. 🤔I am really curious to see if these two changes might resolve this issue.
<img src="https://user-images.githubusercontent.com/106682128/214450884-13bfefdf-4aa2-4bc2-a42f-af333b9ee5bd.png" width="200" />

**Comment by wikd** [comment]
Sorry for the wait. I tried freetube-0.18.0-nightly-348-Android.apk and it works perfectly fine now just default installing without changing anything.
